/**
 * generate-sitemap.js
 * Auto-generates sitemap.xml for ranksorcery.com
 *
 * Scans:
 *   - *.html in repo root
 *   - blog/*.html
 *
 * Usage: node scripts/generate-sitemap.js
 */

const fs   = require('fs');
const path = require('path');

// ── Config ────────────────────────────────────────────────────────────────────
const BASE_URL    = 'https://ranksorcery.com';
const OUTPUT_FILE = path.join(__dirname, '..', 'sitemap.xml');
const REPO_ROOT   = path.join(__dirname, '..');

// Folders to scan (relative to repo root). '' = root itself.
const SCAN_DIRS = ['', 'blog'];

// Files to always exclude (case-insensitive)
const EXCLUDE_FILES = new Set([
  '404.html',
  'google-site-verification.html', // common verification file
]);

// Priority + changefreq rules (matched by URL path, first match wins)
const RULES = [
  { match: /^\/$|^\/index\.html$/i,  priority: '1.0', changefreq: 'daily'   },
  { match: /\/blog\//i,              priority: '0.7', changefreq: 'daily'   },
  { match: /\//,                     priority: '0.8', changefreq: 'weekly'  }, // everything else
];

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Convert a file path to a clean URL path */
function toUrlPath(filePath) {
  // Normalize separators
  let rel = filePath.replace(/\\/g, '/');

  // index.html in root → /
  if (rel === 'index.html') return '/';

  // index.html in subfolder → /folder/
  if (rel.endsWith('/index.html')) return '/' + rel.replace('/index.html', '/');

  // anything else → strip .html
  return '/' + rel.replace(/\.html$/i, '');
}

/** Pick priority + changefreq for a URL path */
function getRules(urlPath) {
  for (const rule of RULES) {
    if (rule.match.test(urlPath)) {
      return { priority: rule.priority, changefreq: rule.changefreq };
    }
  }
  return { priority: '0.5', changefreq: 'monthly' };
}

/** Escape XML special characters */
function escXml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/** Today's date as YYYY-MM-DD */
function today() {
  return new Date().toISOString().split('T')[0];
}

// ── Scan ──────────────────────────────────────────────────────────────────────

const entries = [];
const lastmod = today();

for (const dir of SCAN_DIRS) {
  const absDir = dir ? path.join(REPO_ROOT, dir) : REPO_ROOT;

  if (!fs.existsSync(absDir)) {
    console.warn(`⚠  Directory not found, skipping: ${absDir}`);
    continue;
  }

  const files = fs.readdirSync(absDir).filter(f => f.toLowerCase().endsWith('.html'));

  for (const file of files) {
    const lowerFile = file.toLowerCase();

    // Skip excluded files
    if (EXCLUDE_FILES.has(lowerFile)) {
      console.log(`  ⤼  Excluded: ${dir ? dir + '/' : ''}${file}`);
      continue;
    }

    const relPath  = dir ? `${dir}/${file}` : file;
    const urlPath  = toUrlPath(relPath);
    const fullUrl  = BASE_URL + urlPath;
    const { priority, changefreq } = getRules(urlPath);

    entries.push({ url: fullUrl, lastmod, changefreq, priority });
    console.log(`  ✓  ${fullUrl}  [priority=${priority}, freq=${changefreq}]`);
  }
}

// Sort: root first, then alphabetically
entries.sort((a, b) => {
  if (a.url === BASE_URL + '/') return -1;
  if (b.url === BASE_URL + '/') return  1;
  return a.url.localeCompare(b.url);
});

// ── Build XML ─────────────────────────────────────────────────────────────────

let xml = `<?xml version="1.0" encoding="UTF-8"?>\n`;
xml    += `<!-- Auto-generated by generate-sitemap.js — do not edit manually -->\n`;
xml    += `<!-- Generated: ${new Date().toUTCString()} -->\n`;
xml    += `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n\n`;

for (const e of entries) {
  xml += `  <url>\n`;
  xml += `    <loc>${escXml(e.url)}</loc>\n`;
  xml += `    <lastmod>${e.lastmod}</lastmod>\n`;
  xml += `    <changefreq>${e.changefreq}</changefreq>\n`;
  xml += `    <priority>${e.priority}</priority>\n`;
  xml += `  </url>\n\n`;
}

xml += `</urlset>\n`;

// ── Write ─────────────────────────────────────────────────────────────────────

fs.writeFileSync(OUTPUT_FILE, xml, 'utf8');
console.log(`\n✅ sitemap.xml written → ${OUTPUT_FILE}`);
console.log(`   ${entries.length} URL(s) included.\n`);
